# Generated by Django 4.2 on 2023-05-01 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("scrap", "0003_applynow_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("oid", models.AutoField(primary_key=True, serialize=False)),
                ("collection_type", models.CharField(max_length=100)),
                ("price", models.FloatField()),
                ("address", models.TextField(max_length=255)),
                ("pickup_address", models.TextField(max_length=255)),
                ("drop_address", models.TextField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("pickup_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        )
    ]
